### PR TITLE
Fix clippy lints.

### PR DESCRIPTION
**Pull request by cryptoquick**
I need to have stens on 0.7.1 so I can pull this crate into code I'm using that also uses bp-core and rgb-std.

I updated stens, but it invalidated the test assertions.
Screenshot from 2022-07-13 17-49-59

I'm not sure what the best decision is for that.

### CODE REVIEW

**Comment by cryptoquick** [comment]
@dr-orlovsky For more context on why I need to use these things, I basically want to create a wrapper library around RGB that uses BDK for signing and can be cross-compiled to WASM and an AWS Lambda. For the portions that can't be run in WASM yet (like libsecp256k1) we'll make shim in calls to the Lambda service (NYI).

See: https://github.com/diba-io/bitmask-core/pull/56

Then, this can be easily pulled in to make a desktop wallet also, and eventually we can deprecate the AWS part once libsecp256k1-zkp can be compiled to WASM someday.

**Comment by cryptoquick** [comment]
Haha, I guess you were on it. I merged your latest, but you'll still need to update the test assertions... But I don't want to do it blindly since you have more context as to why those changed.

**Review by dr-orlovsky — APPROVED** [review]
This is all good: new stens breaks tests due to changes in typesystem (I've spotted an optimization there which I did last moment) - so it's ok. I will update the tests. 

Please keep in mind that RGB20 will drastically change in the next days - I need to move things like ticker, name, precision from metadata to be an assigned state for renomination owned type, structured with this stens type system. 

Also, we can do a dedicated RGB21 for NFTs now. The design is there, and doing it in code will take an hr or two of my time. For your migration I assume it will not be a bug effort, due to the fact that RGB20 will also change and require code upgrade. So if you are interested in reviewing and suggesting stuff for RGB21 let's do it together.

**Comment by cryptoquick** [comment]
Perfect, would love to! And make all the changes you like, Rust is a perfect guide. I've been able to keep up with everything so far, your code is very sensible, and very good, properly idiomatic Rust. 🤠

**Comment by dr-orlovsky** [comment]
Thank you for the kind words :) The truth is that I am still learning rust!

**Pull request merged**
