### PR TITLE
Start building the docker image with CI.

### PR DESCRIPTION
**Pull request by monaka**

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Why this is a draft?

**Comment by monaka** [comment]
> Why this is a draft?

Because the patch was tested on my fork diamondhands-rgb/rust-rgb20#1.
I removed the 'draft' tag as I checked it to work fine.

**Review by nicbus — CHANGES_REQUESTED** [review]
looks generally good to me, though I think it's best to update actions to the latest versions before merging

**Review by dr-orlovsky — APPROVED** [review]
ACK 9da2075b3acbb01773d4b214a3285c98853e2dda

**Pull request merged**
